name: "godot-ci export"
on: 
  push:
  workflow_dispatch:

env:
  GODOT_VERSION: 4.2.2
  EXPORT_NAME: GodotBuildTest

jobs:
  run-tests:
    name: Run GUT Tests
    runs-on: ubuntu-20.04
    steps:
     - name: Checkout
       uses: actions/checkout@v4
       with:
         lfs: true
        
     - name: GUT-Tests
       # You may pin to the exact commit or the version.
       # uses: croconut/godot-tester@c0b6cffca6fd87793334bdb9cac050228b43eb74
       uses: croconut/godot-tester@v5.1
       with:
       # Your Godot version number e.g. 3.2.2
         version: 4.2.2
         # Your Godot release type e.g. rc2, beta3
         # Directory containing Gut tests
         # test-dir: res://test/unit # optional, default is res://test
         # Full path to your GUT config file, e.g. 'res://<path>/<config>.json'.
         # config-file: # optional, default is res://.gutconfig.json
         # URL where a precompiled, custom Godot binary will be downloaded and used instead of an official Godot binary.
         # custom-godot-dl-url: # optional, default is 
         # Filename to store and read results in XML
         # result-output-file: # optional, default is test_results.xml
         
     - name: Upload Artifact
       uses: actions/upload-artifact@v4
       with:
        name: TestLog
        path: test_results.xml
    
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    needs: [run-tests]
    container:
      image: barichello/godot-ci:4.2.2
    
    steps:          
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
        
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          godot --headless --verbose --export-release "Windows Desktop" build/windows/$EXPORT_NAME.exe
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: build/windows          
