nname: "godot-ci export"
on: 
  push:
  schedule:
    # nightly test at 22:00 Amsterdam time
    - cron: '0 20 * * *'
  workflow_dispatch:

env:
  GODOT_VERSION: 4.2.2
  EXPORT_NAME: GodotBuildTest

jobs:
  run-tests:
    uses: ./.github/workflows/run-gut-test.yml
    with:
      godot_version: ${{env.GODOT_VERSION}}

  export-builds:
    needs: [run-tests]
    strategy:
      matrix:
        include:
          - { platform: Windows Desktop, export_folder: windows, build_extention: exe }
          - { platform: Mac OSX, export_folder: mac, build_extention: zip }
          
    uses: ./.github/workflows/godot-platform-export.yml
    with:
      platform: ${{ matrix.platform }}
      export_folder: ${{ matrix.export_folder }}
      build_extention: ${{ matrix.build_extention }}
      godot_version: $GODOT_VERSION
      export_name: $EXPORT_NAME
