name: Godot CI/CD

on:
  push: {}
  pull_request: {}

jobs:        
  build:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.2
    strategy:
      matrix:
        platform: [windows]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir -v -p build/${{ matrix.platform }}
          godot --headless --export-release "${{ matrix.platform }}" build/${{ matrix.platform }}/mijn_awesome_game
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform }}-build
          path: build/${{ matrix.platform }}
