name: "godot-ci export"
on: 
  push:
  schedule:
    # nightly test at 22:00 Amsterdam time
    - cron: '0 20 * * *'
  workflow_dispatch:

env:
  GODOT_VERSION: 4.2.2
  EXPORT_NAME: GodotBuildTest

jobs:
  # run-tests:
    # uses: ./.github/workflows/run-gut-test.yml
    # with:
      # godot_version: 4.2.2
    
  export-build:
    name: Windows Export
    runs-on: ubuntu-20.04
    # needs: [run-tests]
    container:
      image: barichello/godot-ci:4.2.2
    strategy:
      matrix: 
        include:
          - { platform_name: "Windows Desktop", build_folder: "windows" }
          - { platform_name: "Mac OSX", build_folder: "mac" }
    
    steps:          
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
        
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          
      - name: Windows Build
        run: |
          mkdir -v -p build/${{matrix.build_folder}}/
          godot --headless --verbose --export-release ${{matrix.platform_name}} build/${{matrix.build_folder}}/$EXPORT_NAME.exe
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.build_folder}}
          path: build/${{matrix.build_folder}}
