name: Godot Platform Export

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      export_folder:
        required: true
        type: string
      build_extention:
        required: true
        type: string

jobs:
  build-for-platform:
    name: Platform Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.2
    
    steps:          
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
        
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          
      - name: Platform Build
        run: |
          mkdir -v -p build/${{matrix.build_folder}}/
          godot --headless --verbose --export-release "${{inputs.platform}}" build/${{inputs.export_folder}}/$EXPORT_NAME.${{inputs.build_extention}}
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{inputs.export_folder}}
          path: build/${{inputs.export_folder}}
