name: Install Godot on Linux

on:
  workflow_dispatch:

jobs:
  install-godot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Update package lists
      run: sudo apt-get update
      
    - name: Install dependencies
      run: sudo apt-get install -y wget unzip
      
    - name: Download Godot
      run: wget --progress=bar:force:noscroll https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
      
    - name: Unzip Godot
      run: unzip Godot_v4.3-stable_linux.x86_64.zip
      
    - name: Make Godot executable
      run: chmod +x Godot_v4.3-stable_linux.x86_64
      
    - name: Move Godot to /usr/local/bin
      run: sudo mv Godot_v4.3-stable_linux.x86_64 /usr/local/bin/godot
      
    - name: Verify Godot installation
      run: godot --version

    - name: install export templates
      run: |
        mkdir -p ~/.local/share/godot/export_templates/4.3-stable
        wget --progress=bar:force:noscroll https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz
        mv templates/* ~/.local/share/godot/export_templates/4.3-stable/
        rm -rf templates
        rm Godot_v4.3-stable_export_templates.tpz
        echo "Export templates installed successfully"
      shell: bash

    - name: Verify installation
      run: |
        if [ -d ~/.local/share/godot/export_templates ]; then
          echo "Export templates directory exists"
          ls -la ~/.local/share/godot/export_templates
        else
          echo "Export templates directory not found"
          exit 1
        fi
      
