name: matrix-test

on:
  workflow_dispatch:

jobs:
  print-job:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        message: ['Hallo', 'World']
        
    steps:
    - name: Print Message
      run: |
        echo "Message: ${{ matrix.message }}"
